ALTER TABLE dristi_case_litigants
ADD COLUMN IF NOT EXISTS first_name VARCHAR(256),
ADD COLUMN IF NOT EXISTS middle_name VARCHAR(256),
ADD COLUMN IF NOT EXISTS last_name VARCHAR(256),
ADD COLUMN IF NOT EXISTS full_name VARCHAR(512),
ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(32),
ADD COLUMN IF NOT EXISTS age VARCHAR(32),
ADD COLUMN IF NOT EXISTS company_name VARCHAR(512),
ADD COLUMN IF NOT EXISTS designation VARCHAR(256),
ADD COLUMN IF NOT EXISTS complainant_type JSONB,
ADD COLUMN IF NOT EXISTS complainant_type_of_entity JSONB,
ADD COLUMN IF NOT EXISTS transferred_poa JSONB,
ADD COLUMN IF NOT EXISTS permanent_address JSONB,
ADD COLUMN IF NOT EXISTS current_address JSONB,
ADD COLUMN IF NOT EXISTS company_address JSONB;


ALTER TABLE dristi_case_poaholders
ADD COLUMN IF NOT EXISTS first_name VARCHAR(256),
ADD COLUMN IF NOT EXISTS middle_name VARCHAR(256),
ADD COLUMN IF NOT EXISTS last_name VARCHAR(256),
ADD COLUMN IF NOT EXISTS full_name VARCHAR(512),
ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(32),
ADD COLUMN IF NOT EXISTS age VARCHAR(32),
ADD COLUMN IF NOT EXISTS address JSONB;