#!/usr/bin/env bash
# Pipeline 2 (dristi-common extraction) — Phases 1-3 only.
#
# Phase 4 (REPLACE — delete duplicate copies + rewrite imports across the
# codebase) is NOT included. Run it explicitly only after reviewing the
# review-needed text and canonical files generated by phases 1-3.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== Phase 1: Inventory ==="
python3 "$SCRIPT_DIR/01_inventory.py"
echo
echo "=== Phase 2: Classify ==="
python3 "$SCRIPT_DIR/02_classify.py"
echo
echo "=== Phase 3: Build canonical classes ==="
python3 "$SCRIPT_DIR/03_build_canonical.py"
echo
echo "=== Phases 1-3 complete ==="
echo
OUT_DIR="scripts/migration/dristi_common/output"
echo "Review before running Phase 4:"
echo "  - $OUT_DIR/dristi_common_classification.csv  (per-class summary)"
echo "  - $OUT_DIR/dristi_common_review_needed.txt   (variants vs canonical)"
echo "  - dristi-monolith/dristi-common/src/main/java (canonical classes)"
