#!/usr/bin/env python3
"""
Pipeline 1 / Phase 2 — Generate module POMs and directory tree.

Creates the per-module subprojects under dristi-monolith/:
  - dristi-common
  - domain-case-lifecycle
  - domain-identity-access
  - domain-integration
  - domain-payments
  - dristi-app

Each module gets:
  - pom.xml inheriting from parent
  - src/main/java/<base-package>/.gitkeep
  - src/main/resources/.gitkeep (only where applicable)
  - src/test/java/<base-package>/.gitkeep
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
MONOLITH_ROOT = REPO_ROOT / "dristi-monolith"

PARENT_GROUP = "org.pucar.dristi"
PARENT_ARTIFACT = "dristi-monolith"
PARENT_VERSION = "1.0.0"

# Modules: (artifactId, base_package_path, description, has_main_resources)
MODULES = [
    (
        "dristi-common",
        "org/pucar/dristi/common",
        "Shared utilities, models, and infrastructure used by all DRISTI modules.",
        True,
    ),
    (
        "domain-case-lifecycle",
        "org/pucar/dristi/caselifecycle",
        "Case lifecycle domain: cases, hearings, orders, tasks, evidence, applications, etc.",
        False,
    ),
    (
        "domain-identity-access",
        "org/pucar/dristi/identity",
        "Identity and access domain: advocates, advocate offices, witnesses.",
        False,
    ),
    (
        "domain-integration",
        "org/pucar/dristi/integration",
        "External integrations: e-sign, summons, treasury, NJDG, ICOPS, e-post, banks.",
        False,
    ),
    (
        "domain-payments",
        "org/pucar/dristi/payments",
        "Payments domain: calculator and payment-related flows.",
        False,
    ),
    (
        "dristi-app",
        "org/pucar/dristi",
        "Bootstrap application — entry point that wires all domain modules together.",
        True,
    ),
]


# Modules that do NOT depend on dristi-common (only dristi-common itself).
NO_COMMON_DEP = {"dristi-common"}

# dristi-app additionally depends on every domain module.
DOMAIN_MODULES = [
    "domain-case-lifecycle",
    "domain-identity-access",
    "domain-integration",
    "domain-payments",
]


def module_pom(artifact: str, description: str) -> str:
    deps_block = ""
    if artifact not in NO_COMMON_DEP:
        deps_block = f"""        <dependency>
            <groupId>{PARENT_GROUP}</groupId>
            <artifactId>dristi-common</artifactId>
            <version>${{project.version}}</version>
        </dependency>
"""

    if artifact == "dristi-app":
        for dm in DOMAIN_MODULES:
            deps_block += f"""        <dependency>
            <groupId>{PARENT_GROUP}</groupId>
            <artifactId>{dm}</artifactId>
            <version>${{project.version}}</version>
        </dependency>
"""

    packaging = "jar"
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  AUTO-GENERATED by scripts/migration/scaffold/02_generate_module_skeletons.py
  Edit only the <dependencies> section as the module gains real classes.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>{PARENT_GROUP}</groupId>
        <artifactId>{PARENT_ARTIFACT}</artifactId>
        <version>{PARENT_VERSION}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>{artifact}</artifactId>
    <packaging>{packaging}</packaging>
    <name>{artifact}</name>
    <description>{description}</description>

    <dependencies>
{deps_block}    </dependencies>
</project>
"""


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def touch_keep(path: Path) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        return False
    path.write_text("", encoding="utf-8")
    return True


def main() -> int:
    if not MONOLITH_ROOT.exists():
        print(f"ERROR: {MONOLITH_ROOT} not found — run Phase 1 first")
        return 1

    written: list[str] = []
    for artifact, base_pkg, description, has_resources in MODULES:
        mod_dir = MONOLITH_ROOT / artifact
        pom_path = mod_dir / "pom.xml"
        # dristi-app's POM is owned by Phase 3 (it has bootstrap-specific deps).
        # Only generate the stub here if it doesn't already exist.
        if artifact == "dristi-app" and pom_path.exists():
            pass
        elif write_if_changed(pom_path, module_pom(artifact, description)):
            written.append(str(pom_path.relative_to(REPO_ROOT)))

        # Source/test trees
        main_src = mod_dir / "src" / "main" / "java" / base_pkg / ".gitkeep"
        test_src = mod_dir / "src" / "test" / "java" / base_pkg / ".gitkeep"
        if touch_keep(main_src):
            written.append(str(main_src.relative_to(REPO_ROOT)))
        if touch_keep(test_src):
            written.append(str(test_src.relative_to(REPO_ROOT)))

        if has_resources:
            res_keep = mod_dir / "src" / "main" / "resources" / ".gitkeep"
            if touch_keep(res_keep):
                written.append(str(res_keep.relative_to(REPO_ROOT)))

    print(f"Wrote/updated {len(written)} files:")
    for path in written:
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
