#!/usr/bin/env python3
"""
Pipeline 1 / Phase 3 — Generate bootstrap application.

Writes into dristi-monolith/dristi-app/:
  - pom.xml (replaces the minimal stub from Phase 2 — adds Spring Boot starter,
    Spring Modulith dependencies, and spring-boot-maven-plugin executable build)
  - src/main/java/org/pucar/dristi/DristiApplication.java
  - src/main/resources/application.yml
  - src/test/java/org/pucar/dristi/ModuleStructureTest.java

Spring Modulith version pinned for Spring Boot 3.2.x compatibility.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
APP_DIR = REPO_ROOT / "dristi-monolith" / "dristi-app"

PARENT_GROUP = "org.pucar.dristi"
PARENT_ARTIFACT = "dristi-monolith"
PARENT_VERSION = "1.0.0"

SPRING_MODULITH_VERSION = "1.1.6"  # compatible with Spring Boot 3.2.x

DOMAIN_MODULES = [
    "domain-case-lifecycle",
    "domain-identity-access",
    "domain-integration",
    "domain-payments",
]


APP_POM = f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  AUTO-GENERATED by scripts/migration/scaffold/03_generate_bootstrap_app.py
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>{PARENT_GROUP}</groupId>
        <artifactId>{PARENT_ARTIFACT}</artifactId>
        <version>{PARENT_VERSION}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>dristi-app</artifactId>
    <packaging>jar</packaging>
    <name>dristi-app</name>
    <description>Bootstrap application — wires all domain modules into a single deployable.</description>

    <properties>
        <spring-modulith.version>{SPRING_MODULITH_VERSION}</spring-modulith.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.modulith</groupId>
                <artifactId>spring-modulith-bom</artifactId>
                <version>${{spring-modulith.version}}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>{PARENT_GROUP}</groupId>
            <artifactId>dristi-common</artifactId>
            <version>${{project.version}}</version>
        </dependency>
{chr(10).join(
    f'''        <dependency>
            <groupId>{PARENT_GROUP}</groupId>
            <artifactId>{m}</artifactId>
            <version>${{project.version}}</version>
        </dependency>'''
    for m in DOMAIN_MODULES
)}

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-starter-core</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.modulith</groupId>
            <artifactId>spring-modulith-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
"""

DRISTI_APPLICATION_JAVA = """package org.pucar.dristi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.modulith.Modulithic;

/**
 * Single entry-point for the DRISTI modular monolith.
 * <p>
 * The {@link Modulithic} annotation declares the application as a Spring Modulith
 * project so that module boundaries can be verified at build/test time.
 */
@SpringBootApplication
@Modulithic(systemName = "dristi", sharedModules = "common")
public class DristiApplication {

    public static void main(String[] args) {
        SpringApplication.run(DristiApplication.class, args);
    }
}
"""

APPLICATION_YML = """# Auto-generated bootstrap config — extended by Pipeline 5 (Config Consolidation).
server:
  port: 8080

spring:
  application:
    name: dristi-monolith
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
"""

MODULE_STRUCTURE_TEST_JAVA = """package org.pucar.dristi;

import org.junit.jupiter.api.Test;
import org.springframework.modulith.core.ApplicationModules;

/**
 * Verifies Spring Modulith module structure.
 * Fails the build if any module crosses another module's `internal` boundary
 * or if a cyclic dependency between modules is introduced.
 */
class ModuleStructureTest {

    @Test
    void verifyModuleStructure() {
        ApplicationModules.of(DristiApplication.class).verify();
    }
}
"""


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path.relative_to(REPO_ROOT)}")


def remove_if_exists(path: Path) -> None:
    if path.exists():
        path.unlink()
        print(f"  removed {path.relative_to(REPO_ROOT)}")


def main() -> int:
    if not APP_DIR.exists():
        print(f"ERROR: {APP_DIR} not found — run Phase 2 first")
        return 1

    write(APP_DIR / "pom.xml", APP_POM)
    write(
        APP_DIR / "src" / "main" / "java" / "org" / "pucar" / "dristi" / "DristiApplication.java",
        DRISTI_APPLICATION_JAVA,
    )
    write(APP_DIR / "src" / "main" / "resources" / "application.yml", APPLICATION_YML)
    write(
        APP_DIR / "src" / "test" / "java" / "org" / "pucar" / "dristi" / "ModuleStructureTest.java",
        MODULE_STRUCTURE_TEST_JAVA,
    )

    # Clean up the .gitkeep stubs from Phase 2 wherever real files now exist.
    for keep in [
        APP_DIR / "src" / "main" / "java" / "org" / "pucar" / "dristi" / ".gitkeep",
        APP_DIR / "src" / "main" / "resources" / ".gitkeep",
        APP_DIR / "src" / "test" / "java" / "org" / "pucar" / "dristi" / ".gitkeep",
    ]:
        remove_if_exists(keep)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
